### ISSUE TITLE
How to load MS text translator API

### ISSUE THREAD

**Issue by jaelim** [Microsoft/acceleratoRs#2]
Hello,
I'm running your code to understand. At the end of the source code, there's a step where you use MS translator API. I'm having a difficulty to load the API key with the following code line. Any tips might be appreciated.

`source("path_to_your_confidential_information")`

**Comment by yueguoguo** [comment]
Hi @jaelim the API key is obtained from your Azure subscription. See https://www.microsoft.com/cognitive-services/en-us/translator-api for more information. HTH. 

Let me know you have problem using the package or API. 

Cheers
Le

**Comment by jaelim** [comment]
@yueguoguo languageR doesn't seem to have cognitiveTranslation. Could you please double check?

**Comment by yueguoguo** [comment]
Hi @jaelim did you install the package from here - https://github.com/yueguoguo/Azure-R-Interface/blob/master/utils/languageR/? Looks like the function is there, but do let me know if you still have issues. 

Cheers
Le

**Comment by jaelim** [comment]
@yueguoguo No, I installed it directly from CRAN site: https://cran.r-project.org/web/packages/languageR/index.html
Now, I understand why it wasn't working because they are the two different packages.

**Comment by yueguoguo** [comment]
Hi @jaelim I have changed package name and provided installation instructions. Please take it a go and see if it works well. Thanks.
