### ISSUE TITLE
No data in Data folder

### ISSUE THREAD

**Issue by anhhd** [Microsoft/acceleratoRs#3]
Hi Microsoft team, 
Your project is great. However, I could not find data in CreditRiskPrediction project.
Could you update data?

**Comment by Triamus** [comment]
Actually there is data but the description says "```Link to the Full Data Set```" and gives a size e.g. for ```transactionSimu.csv``` of ```22,565 kb``` but when following the link the file ```acceleratoRs / CreditRiskPrediction / Data / transactionSimu_v3.csv``` has only ```1.11 mb``` and seems to have the shape of the reduced dataset. @ZhouFang928 could you please check? Many thanks!

**Comment by ZhouFang928** [comment]
Hi all,
We used simulated dataset of larger size (described in the data description) to generate the html file for credit risk prediction and then reduced the size of the data in the repo so as to shorten the processing time. People can get the result more quickly by using the smaller data set for demonstration and learning purpose.

**Comment by anhhd** [comment]
Thanks a lot for your updating.
I have had data and played with it.
Rgds

Anh
