### ISSUE TITLE
CreditRiskPrediction Data Oddities

### ISSUE THREAD

**Issue by topepo** [Microsoft/acceleratoRs#6]
I might use the credit risk prediction data for teaching so I have a few questions: 

1. There are a lot of negative values for `creditLimit` and `income`. Is there are reason for this?

1. The distribution for `income` is fairly pathological. Is this common for the situation or an issue with the simulation? 

Thanks

(edited since I figured one question out)

**Comment by hongooi73** [comment]
Negative income is possible, if your outflows exceed your gross income.

By pathological, do you mean an extreme right tail? That's also quite possible.

**Comment by gjwgit** [comment]
The task is to identify customers who are not such a good credit risk for a
bank.

I believe both creditLimit and income are normalised.

Regards,
Graham
