### ISSUE TITLE
ProductDemandForecast - links to data files broken

### ISSUE THREAD

**Issue by QuantMonk** [Microsoft/acceleratoRs#7]
Hi Team, I have just started exploring accelaratoRs templates and started with ProductDemandForecast. In the below data page, the links to the csv files seem to be broken. Can some one please look into this?

Page where issue is found: https://github.com/Microsoft/acceleratoRs/tree/master/ProductDemandForecast/Data

Non working links on the page:
1. https://github.com/Microsoft/acceleratoRs/blob/master/ProductDemandForecast/Data/productQuantity.csv
2. https://github.com/Microsoft/acceleratoRs/blob/master/ProductDemandForecast/Data/productCategory.csv

**Comment by ZhouFang928** [comment]
Hi Quant, I haven't completely finished the product demand forecasting template and was planning to upload the data later. Thanks for your patience to wait.
