### ISSUE TITLE
problem with genSequence function

### ISSUE THREAD

**Issue by demillan** [Microsoft/acceleratoRs#8]
Hi, I'm trying to reproduce the tutorial locally and I have the following error:

```
> seq_train <- genSequence(df_train)
Generating data ...
Error in y[index, 1] <- reading_y : 
  number of items to replace is not a multiple of replacement length
```

I'm running it on Windows 10 with Microsoft R Open 3.4.1.

**Comment by yueguoguo** [comment]
Hey @demillan sorry for belated reply. Can you point to which of the tutorials you are referring to? Thanks!

**Comment by demillan** [comment]
Solar Panel Forecasting

https://github.com/Microsoft/acceleratoRs/blob/master/SolarPanelForecasting/Code/SolarPanelForecastingCode.Rmd

Thanks.

**Comment by yueguoguo** [comment]
Hi @demillan the bug was fixed. Please try again and let me know if it works. Cheers.

**Comment by demillan** [comment]
Hi @yueguoguo, it seems to be fixed. Thanks!

**Comment by yueguoguo** [comment]
@demillan Cool glad to hear that. :)
